server:
   port: ${PORT:9080}
application:
   name: ^project.artifactId^
   description: ^project.name^
   version: ^project.version^
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        clientId: client
        clientSecret: client
        accessTokenUri: lb://auth/oauth/token
        userAuthorizationUri: lb://auth/oauth/authorize
      resource:
        jwk:
          key-set-uri: lb://auth/.well-known/jwks.json
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/customers/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}

      - id: auth
        uri: lb://auth
        predicates:
        - Path=/api/users/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}

      - id: auth-token
        uri: lb://auth
        predicates:
        - Path=/oauth/token
        filters:
        - RewritePath=/(?<path>.*), /$\{path}


      - id: loan-applications-service
        uri: lb://loan-applications-service
        predicates:
        - Path=/api/loanapplications

management:
  security:
    enabled: false

 
      