server:
  port: ${PORT:9182}

spring:
  application:
    name: loan-applications-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}