server:
  port: ${PORT:9182}

spring:
  application:
    name: loan-applications-service
  security:
    oauth2:
      client:
        client-id: client
        client-secret: secret
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:${user.home}/.h2/loandb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas:
      - PUBLIC

customer-service:
  name: customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}